version: 0.2

env:
  parameter-store:
    API_KEY: "KIS-API-KEY"
    API_SECRET: "KIS-API-SECRET"

phases:
  install:
    runtime-versions:
      java: latest
  pre_build:
    commands:
      - echo "Fetching parameters"
      - echo "Parameters fetched"
      - echo "Generating application.properties file"
      - "echo 'api.secret.key=${API_KEY}' > src/main/resources/application-secrets.properties"
      - "echo 'api.secret.secret=${API_SECRET}' >> src/main/resources/application-secrets.properties"
      - echo "Generating application.yml file"
      - "echo 'token: placeholder' > src/main/resources/application-secrets.yml"
      - "echo 'tokenType: Bearer' >> src/main/resources/application-secrets.yml"
      - chmod +x gradlew
  build:
    on-failure: ABORT
    commands:
      - "./gradlew build"
  post_build:
    commands:
      - "zip build/libs/artifact.zip build/libs/*.war"
artifacts:
  files:
    - "build/libs/*"
  name: "artifact-after-build-$(%Y-%m-%d-%M:%S).zip"
  discard-paths: yes
